networks:
  music-store-network:
    driver: bridge

volumes:
  email-db-data:

services:
  email-db:
    image: postgres:latest
    container_name: email-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: email
    ports:
      - "5432:5432"
    networks:
      - music-store-network
    volumes:
      - email-db-data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - music-store-network
  
  email-service:
    build: .
    container_name: email-service
    ports:
      - "8080:8080"
    # env_file:
    #   - .env
    environment:
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
    depends_on:
      - email-db
      - rabbitmq
    networks:
      - music-store-network
